[package]
name = "wire"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.7.3"
serde = "1.0.136"
serde_derive = "1.0.136"
thiserror = "1.0.40"
spinners = "4.1.0"
